In [4]:
# each column is Data Frame is Called "----SERIES----"
import pandas as pd

df = pd.DataFrame([[34,42,53,94],[65,83,23,78]], columns=['A','B','C','D'],index='X Y'.split())
print(df)

    A   B   C   D
X  34  42  53  94
Y  65  83  23  78

In [ ]:
df.index  #gives all the row names

Index(['X', 'Y'], dtype='object')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.shape

(2, 4)

In [ ]:
df.values

array([[34, 42, 53, 94],
       [65, 83, 23, 78]])

In [ ]:
# to Generate Random data
import numpy as np
df= pd.DataFrame(np.random.randint(0,100,(5,5)),columns='A B C D E'.split(),index="X Y Z P Q".split())
print(df)

    A   B   C   D   E
X  83  64  43   7  39
Y  67  60  72  13  49
Z  36  94   5  60  12
P   5  86  75  95  48
Q  18  48  40  19  57

#Real Data set Working

In [5]:
df1= pd.read_excel('/content/drive/MyDrive/DataSet for pandas/Sample - Superstore.xls')

In [ ]:
df1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df1.index

RangeIndex(start=0, stop=9994, step=1)

In [ ]:
df1.iloc[0:1,:]  #same as numpy just add ----dataset_name.iloc------

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [ ]:
df1.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
df1.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [ ]:
#if i need specific columns
df1[['Customer ID','Country']]

     Customer ID        Country
0       CG-12520  United States
1       CG-12520  United States
2       DV-13045  United States
3       SO-20335  United States
4       SO-20335  United States
...          ...            ...
9989    TB-21400  United States
9990    DB-13060  United States
9991    DB-13060  United States
9992    DB-13060  United States
9993    CC-12220  United States

[9994 rows x 2 columns]

# Append means (add below the table)
# concat means (add to right side of table)
# concat axis=0  append below
# concat axis=1 append right

In [ ]:
#for join a 2 tables use syntax as merge
#inner = pd.merge(table1,table2, on= '',how ='inner')

In [ ]:
# to make any column as index name (row name)
# then df.set_index('column name',inplace=true)
# inplace=true this makes changes permanents

In [ ]:
#df.reset_index()  makesback to original
# df.reset_index(inplace=true)

In [ ]:
df1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
# df1['Customer Name'].unique()  gives unique values in that column
df1['Customer Name'].nunique() # counts  unique values

793

In [ ]:
df1['City'].head(10).value_counts()  # counts no of value repeating in that selected column

City
Los Angeles        6
Henderson          2
Fort Lauderdale    2
Name: count, dtype: int64

In [ ]:
df1['City'].head(10).value_counts(normalize=True)  # gives percentage

City
Los Angeles        0.6
Henderson          0.2
Fort Lauderdale    0.2
Name: proportion, dtype: float64

In [ ]:
df1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df1.groupby('City')['Sales'].sum()  # if u want to analyse between one dimension and one measure use groupby

City
Aberdeen         25.500
Abilene           1.392
Akron          2729.986
Albuquerque    2220.160
Alexandria     5519.570
                 ...
Woonsocket      195.550
Yonkers        7657.666
York            817.978
Yucaipa          50.800
Yuma            840.865
Name: Sales, Length: 531, dtype: float64

In [ ]:
df1.groupby('City')['Sales'].min()

City
Aberdeen       25.500
Abilene         1.392
Akron           2.286
Albuquerque     4.280
Alexandria     12.420
                ...
Woonsocket     45.360
Yonkers        10.896
York           37.896
Yucaipa        50.800
Yuma           10.496
Name: Sales, Length: 531, dtype: float64

In [ ]:
df1.groupby('City')['Sales'].describe().head()  # gives all min,max,std,mean and all

,count,mean,std,min,25%,50%,75%,max
City,,,,,,,,
Aberdeen,1.0,25.500000,NaN,25.500,25.5000,25.500,25.5000,25.500
Abilene,1.0,1.392000,NaN,1.392,1.3920,1.392,1.3920,1.392
Akron,21.0,129.999333,168.318749,2.286,14.3520,25.560,247.1880,665.408
Albuquerque,14.0,158.582857,161.967111,4.280,36.3075,104.525,245.6250,595.000
Alexandria,16.0,344.973125,1025.875022,12.420,22.0800,27.025,163.5075,4164.050

In [ ]:
#calculate region wise sales
df1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
df1.groupby(['Region','Category'])[['Sales','Profit']].count()

                         Sales  Profit
Region  Category
Central Furniture          481     481
        Office Supplies   1422    1422
        Technology         420     420
East    Furniture          601     601
        Office Supplies   1712    1712
        Technology         535     535
South   Furniture          332     332
        Office Supplies    995     995
        Technology         293     293
West    Furniture          707     707
        Office Supplies   1897    1897
        Technology         599     599

In [11]:
# want to analyse between 2 dimensions column then use crosstab
pd.crosstab(df1['Region'],df1['Category'])

Category  Furniture  Office Supplies  Technology
Region
Central         481             1422         420
East            601             1712         535
South           332              995         293
West            707             1897         599

In [15]:
df1['Category'].head()

0          Furniture
1          Furniture
2    Office Supplies
3          Furniture
4    Office Supplies
Name: Category, dtype: object

In [13]:
pd.get_dummies(df1['Category']).head()

   Furniture  Office Supplies  Technology
0       True            False       False
1       True            False       False
2      False             True       False
3       True            False       False
4      False             True       False

In [21]:
pd.cut(df1['Sales'], bins=[0,50,500,1000],labels=['low','Med','High']).head()  #cut is used like range if 0 to 50 then low like that

0     Med
1    High
2     low
3    High
4     low
Name: Sales, dtype: category
Categories (3, object): ['low' < 'Med' < 'High']

In [19]:
df1['Sales'].head()

0    261.9600
1    731.9400
2     14.6200
3    957.5775
4     22.3680
Name: Sales, dtype: float64